language: R
cache: packages

install:
  - Rscript -e 'install.packages("bookdown")'
script:
  - cd doc && Rscript -e 'bookdown::render_book("index.md")'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: doc/build
  on:
    branch: master
